[[ISSUERS]]
address = "rh7SidU91xGW2Za5RvoKiCgS2YB2psTBgq"
name = "Sailing Frog's Leap"

[[TOKENS]]
issuer = "rh7SidU91xGW2Za5RvoKiCgS2YB2psTBgq"
currency = "LEAP"
name = "LEAP"
desc = "The community token of Sailing Frog's Leap."
icon = "https://sailingfrogsleap.com/leap-logo.png"
